import mongoose, { Schema } from "mongoose";
import bcrypt from "bcrypt";

const userSchema = new Schema(
  {
    username: {
      type: String,
      require: true,
      trim: true,
      unique: true,
      lowercase: true,
      index: true,
    },
    hash_password: {
      type: String,
      require: true,
    },
    profilePicture: {
      type: String,
    },
    travelJournal: {
      type: Array,
      default: [
        {
          countryname: "andorra",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "austria",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "belgium",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "denmark",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "finland",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "france",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "germany",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "greece",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "iceland",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "ireland",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "italy",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "liechenstein",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "luxembourg",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "malta",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "monaco",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "netherlands",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "norway",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "portugal",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "sanmarino",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "spain",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "sweden",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "switzerland",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "turkey",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
        {
          countryname: "unitedkingdom",
          isComplete: false,
          isQ1Correct: false,
          isQ2Correct: false,
          isQ3Correct: false,
          isQ4Correct: false,
          isQ5Correct: false,
        },
      ],
    },
  },
  { timestamps: true }
);

userSchema.method({
  async authenticate(password) {
    return bcrypt.compare(password, this.hash_password);
  },
});

export default mongoose.model("User", userSchema, "users");
