import mongoose, { Schema } from 'mongoose';
import bcrypt from 'bcrypt';

const userSchema = new Schema(
  {
    username: {
      type: String,
      require: true,
      trim: true,
      unique: true,
      lowercase: true,
      index: true,
    },
    hash_password: {
      type: String,
      require: true,
    },
    profilePicture: {
      type: String,
    },
    travelJournal: {
      type: Array,
      default: [
        {
          countryname: 'andorra',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'austria',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'belgium',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'denmark',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'finland',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'france',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'germany',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'greece',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'iceland',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'ireland',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'italy',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'liechenstein',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'luxembourg',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'malta',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'monaco',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'netherlands',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'norway',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'portugal',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'sanmarino',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'spain',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'sweden',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'switzerland',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'turkey',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
        {
          countryname: 'unitedkingdom',
          isComplete: false,
          question1Correct: false,
          question2Correct: false,
          question3Correct: false,
          question4Correct: false,
          question5Correct: false,
        },
      ],
    },
  },
  { timestamps: true }
);

userSchema.method({
  async authenticate(password) {
    return bcrypt.compare(password, this.hash_password);
  },
});

export default mongoose.model('User', userSchema, 'users');
